services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8800:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'      
          memory: 512M      

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
      args:
        - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
        - ADMIN_SALT=${ADMIN_SALT}
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '1.0'       
          memory: 1G        

volumes:
  mysql_data:
    # Define volume for persisting MySQL data
